(function (window) {
  function normalizeCountry(value) {
    if (!value) return '';
    var v = String(value).trim().toLowerCase();

    var map = {
        "afghanistan": "AF",
        "albania": "AL",
        "algeria": "DZ",
        "andorra": "AD",
        "angola": "AO",
        "argentina": "AR",
        "armenia": "AM",
        "australia": "AU",
        "austria": "AT",
        "bahamas": "BS",
        "bahrain": "BH",
        "bangladesh": "BD",
        "barbados": "BB",
        "belgium": "BE",
        "belize": "BZ",
        "benin": "BJ",
        "bhutan": "BT",
        "bolivia": "BO",
        "bosnia and herzegovina": "BA",
        "botswana": "BW",
        "brazil": "BR",
        "bulgaria": "BG",
        "cambodia": "KH",
        "cameroon": "CM",
        "canada": "CA",
        "chile": "CL",
        "china": "CN",
        "colombia": "CO",
        "costa rica": "CR",
        "croatia": "HR",
        "cyprus": "CY",
        "czech republic": "CZ",
        "denmark": "DK",
        "dominican republic": "DO",
        "ecuador": "EC",
        "egypt": "EG",
        "estonia": "EE",
        "ethiopia": "ET",
        "finland": "FI",
        "france": "FR",
        "germany": "DE",
        "ghana": "GH",
        "greece": "GR",
        "greenland": "GL",
        "guatemala": "GT",
        "haiti": "HT",
        "honduras": "HN",
        "hong kong": "HK",
        "hungary": "HU",
        "iceland": "IS",
        "india": "IN",
        "indonesia": "ID",
        "ireland": "IE",
        "israel": "IL",
        "italy": "IT",
        "jamaica": "JM",
        "japan": "JP",
        "jordan": "JO",
        "kenya": "KE",
        "kuwait": "KW",
        "latvia": "LV",
        "lebanon": "LB",
        "lithuania": "LT",
        "luxembourg": "LU",
        "malaysia": "MY",
        "malta": "MT",
        "mexico": "MX",
        "monaco": "MC",
        "morocco": "MA",
        "namibia": "NA",
        "nepal": "NP",
        "netherlands": "NL",
        "new zealand": "NZ",
        "nigeria": "NG",
        "norway": "NO",
        "oman": "OM",
        "pakistan": "PK",
        "panama": "PA",
        "paraguay": "PY",
        "peru": "PE",
        "philippines": "PH",
        "poland": "PL",
        "portugal": "PT",
        "qatar": "QA",
        "romania": "RO",
        "russia": "RU",
        "saudi arabia": "SA",
        "senegal": "SN",
        "serbia": "RS",
        "singapore": "SG",
        "slovakia": "SK",
        "slovenia": "SI",
        "south africa": "ZA",
        "south korea": "KR",
        "spain": "ES",
        "sri lanka": "LK",
        "sweden": "SE",
        "switzerland": "CH",
        "taiwan": "TW",
        "thailand": "TH",
        "tunisia": "TN",
        "turkey": "TR",
        "ukraine": "UA",
        "united arab emirates": "AE",
        "united kingdom": "GB",
        "united states": "US",
        "uruguay": "UY",
        "vietnam": "VN",
        "zambia": "ZM",
        "zimbabwe": "ZW",
     };

    if (/^[a-z]{2}$/i.test(v)) return v.toUpperCase();
    return map[v] || value.toUpperCase();
  }

  window.normalizeCountry = normalizeCountry;
})(window);